---
spring:
  config.activate.on-profile: default
  sql:
     init:
      mode: never
  datasource:
    url: "jdbc:sqlite:/home/user/projects/bookstore/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never 

    hikari:
        maximum-pool-size: 1
        max-lifetime: 0

cds:
  datasource:
    auto-config.enabled: false

